export const GET_FILM_HOME_POPULAR = 'GET_FILM_HOME_POPULAR'; 
export const GET_UPCOMING_FILM_HOME = 'GET_UPCOMING_FILM_HOME';

export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_TOP_RATED_TV = 'GET_TOP_RATED_TV';
export const GET_POPULAR_TV = 'GET_POPULAR_TV';


export const GET_SEARCH_FILM = 'GET_SEARCH_FILM';

export const HIDE_SEARCH_FILM = 'HIDE_SEARCH_FILM';