

export const SET_VISIBLE = 'SET_VISIBLE';

export const SET_INVISIBLE = 'SET_INVISIBLE'; 



export const SHOW_OVERLAY = 'SHOW_OVERLAY';

export const HIDE_OVERLAY = 'HIDE_OVERLAY';

export const GET_COMPONENT_CONTENT = 'GET_COMPONENT_CONTENT'



export const SET_LOADING = 'SET_LOADING';

export const SET_HIDE_LOADING = 'SET_HIDE_LOADING';